Repository TAHIR0110/ThereForYou, pull requests merged in 2024-06, with the labels that each got.

#131 Covid-19 X-Ray Image Classification
  COVID19-X Ray  Image Classification/Dataset/README.md
  COVID19-X Ray  Image Classification/Images/DenseNet121_predictions/0e775fe9-7a73-49cd-bf74-3fa33f76e2a5.png
  COVID19-X Ray  Image Classification/Images/DenseNet121_predictions/5ef690cb-9c3b-476b-8aeb-c63847941837.png
  COVID19-X Ray  Image Classification/Images/DenseNet121_predictions/7e024ac4-f3b4-4832-a776-0c2bb93b2c56.png
  COVID19-X Ray  Image Classification/Images/DenseNet121_predictions/8af20033-5829-4bdc-aeef-db9b5f63c387.png
  COVID19-X Ray  Image Classification/Images/InceptionV3_predictions/54a01ad5-ad98-4506-94a6-51cf178b3c4d.png
  COVID19-X Ray  Image Classification/Images/InceptionV3_predictions/55c53623-3f9b-4cf3-8624-7a509b7e7478.png
  COVID19-X Ray  Image Classification/Images/InceptionV3_predictions/8b73d11e-6df6-4332-9807-d0e37e2bb100.png
  COVID19-X Ray  Image Classification/Images/InceptionV3_predictions/9f819a75-9fca-4a51-99ac-097194a7d43e.png
  COVID19-X Ray  Image Classification/Images/MobieNetV2_predictions/4d8f7d2a-3ef1-4942-820b-3055bb4dc16f.png
  COVID19-X Ray  Image Classification/Images/MobieNetV2_predictions/6bbe9b43-1bc7-47e1-9aaa-69b4fa8ef1c6.png
  COVID19-X Ray  Image Classification/Images/MobieNetV2_predictions/92336470-2301-4a96-9a6e-fba21558bff6.png
  COVID19-X Ray  Image Classification/Images/MobieNetV2_predictions/feaf9857-f711-41b8-8086-343dc8610c46.png
  COVID19-X Ray  Image Classification/Images/VGG16_predictions/04701e86-c359-4103-899a-55faa0e6ea08.png
  COVID19-X Ray  Image Classification/Images/VGG16_predictions/4baaf1a6-0eed-4833-bf01-21628c39cf0e.png
  COVID19-X Ray  Image Classification/Images/VGG16_predictions/4e652e15-23c6-4317-861f-9bd5d14a5940.png
  COVID19-X Ray  Image Classification/Images/VGG16_predictions/af7f9523-cc21-454a-8f1c-35facfb2a89e.png
  COVID19-X Ray  Image Classification/Images/Xception_predictions/61a8aed3-bd82-4ff9-8ab9-5dd37a41d889.png
  COVID19-X Ray  Image Classification/Images/Xception_predictions/86bf04a4-43cc-4741-b300-8ad978c46132.png
  COVID19-X Ray  Image Classification/Images/Xception_predictions/89435ec5-a3b2-4942-a735-3ec28f9a918c.png
  COVID19-X Ray  Image Classification/Images/Xception_predictions/fb82b37b-d970-48cc-a159-8e9587f35f1a.png
  COVID19-X Ray  Image Classification/Images/bar_chart.png
  COVID19-X Ray  Image Classification/Images/image_path_distribution.png
  COVID19-X Ray  Image Classification/Images/pie.png
  COVID19-X Ray  Image Classification/Models/README.md
  COVID19-X Ray  Image Classification/Models/models_COVID_19.ipynb
  COVID19-X Ray  Image Classification/requirement.txt
Labels: enhancement, level2, gssoc

#127 Traffic Sign Detection for visually impaired
  Traffic_Sign_Detection_for_visually_impaired/dataset/README.md
  Traffic_Sign_Detection_for_visually_impaired/images/ResNet50_prediction/don't_go_straight.png
  Traffic_Sign_Detection_for_visually_impaired/images/ResNet50_prediction/go_left_or_straight.png
  Traffic_Sign_Detection_for_visually_impaired/images/ResNet50_prediction/go_right-or_straight.png
  Traffic_Sign_Detection_for_visually_impaired/images/ResNet50_prediction/roundabout_mandatory.png
  Traffic_Sign_Detection_for_visually_impaired/images/ResNet50_prediction/speed_limit_60.png
  Traffic_Sign_Detection_for_visually_impaired/images/ResNet50_prediction/speed_limit_80.png
  Traffic_Sign_Detection_for_visually_impaired/images/VGG16_prediction/don't_go_straight.png
  Traffic_Sign_Detection_for_visually_impaired/images/VGG16_prediction/go_right.png
  Traffic_Sign_Detection_for_visually_impaired/images/VGG16_prediction/go_right2.png
  Traffic_Sign_Detection_for_visually_impaired/images/VGG16_prediction/go_right_and_straight.png
  Traffic_Sign_Detection_for_visually_impaired/images/VGG16_prediction/speed_limit_60.png
  Traffic_Sign_Detection_for_visually_impaired/images/VGG16_prediction/speed_limit_80.png
  Traffic_Sign_Detection_for_visually_impaired/images/Xception_prediction/Don't_go_straight.png
  Traffic_Sign_Detection_for_visually_impaired/images/Xception_prediction/Roundabout_mandatory.png
  Traffic_Sign_Detection_for_visually_impaired/images/Xception_prediction/go_right_or_straight.png
  Traffic_Sign_Detection_for_visually_impaired/images/Xception_prediction/roundabout_mandatory2.png
  Traffic_Sign_Detection_for_visually_impaired/images/Xception_prediction/speed_limit_60.png
  Traffic_Sign_Detection_for_visually_impaired/images/Xception_prediction/speed_limit_80Km.png
  Traffic_Sign_Detection_for_visually_impaired/images/bar.png
  Traffic_Sign_Detection_for_visually_impaired/images/cross_tabulation.png
  Traffic_Sign_Detection_for_visually_impaired/images/image_path_distribution.png
  Traffic_Sign_Detection_for_visually_impaired/images/pie_chart.png
  Traffic_Sign_Detection_for_visually_impaired/models/README.md
  Traffic_Sign_Detection_for_visually_impaired/models/models_TrafficSignDetection.ipynb
  Traffic_Sign_Detection_for_visually_impaired/requirement.txt
Labels: enhancement, level2, gssoc

#140 Brain Tumor Detection
  Brain Tumor Detection/Dataset/README.md
  Brain Tumor Detection/Images/DenseNet121/34527189-008a-4db2-96ee-ddcbe8994926.png
  Brain Tumor Detection/Images/DenseNet121/5fd59feb-d114-4aa6-b81b-71ac541bb884.png
  Brain Tumor Detection/Images/DenseNet121/81b76804-a42a-47fb-8a37-b743664af234.png
  Brain Tumor Detection/Images/DenseNet121/f4e50ab1-3c2d-426a-b11b-b2d6c2e0e1a3.png
  Brain Tumor Detection/Images/InceptionV3_predictions/04794cc7-d5b7-4ecc-b0a9-35f18c1ebf15.png
  Brain Tumor Detection/Images/InceptionV3_predictions/13462d45-4027-4207-be4e-a483cee5bb51.png
  Brain Tumor Detection/Images/InceptionV3_predictions/6f28d911-f7b4-4e11-a86a-f7fe372600ae.png
  Brain Tumor Detection/Images/InceptionV3_predictions/bb460701-375f-4050-ac83-9b85836db058.png
  Brain Tumor Detection/Images/ResNet101V2_predictions/03a977fd-9400-46c8-9233-c9a4097fac07.png
  Brain Tumor Detection/Images/ResNet101V2_predictions/12114c34-012f-40d9-980f-4152ef2fbf60.png
  Brain Tumor Detection/Images/ResNet101V2_predictions/33a24aa6-b8b5-40d7-9903-77faaee5276a.png
  Brain Tumor Detection/Images/ResNet101V2_predictions/b1962cdd-9012-4b82-93f5-21a6a3a4188f.png
  Brain Tumor Detection/Images/Resnet50V2_predictions/3b7cb05f-555b-4b83-ab6e-c9c66f04ebab.png
  Brain Tumor Detection/Images/Resnet50V2_predictions/4095f7df-54e0-4bda-9e82-647ba9e52d06.png
  Brain Tumor Detection/Images/Resnet50V2_predictions/b35aec0b-f342-4954-8aa0-be87dfdd1956.png
  Brain Tumor Detection/Images/Resnet50V2_predictions/b7b638ba-f76d-4f9a-9c75-136451a8964d.png
  Brain Tumor Detection/Images/Xception_predictions/34f1e7e1-b284-412f-8f39-e275b51ab1da.png
  Brain Tumor Detection/Images/Xception_predictions/5d2e80b8-a395-455f-9fd9-8abd5b066c87.png
  Brain Tumor Detection/Images/Xception_predictions/cff8b585-8231-46b5-beb4-e21fae88a673.png
  Brain Tumor Detection/Images/Xception_predictions/fd604494-b52f-4f9e-a6b0-b7756c65c18d.png
  Brain Tumor Detection/Images/bar.png
  Brain Tumor Detection/Images/image_path_distribution.png
  Brain Tumor Detection/Images/pie.png
  Brain Tumor Detection/Models/README.md
  Brain Tumor Detection/Models/models_Brain_Tumor_detection.ipynb
  Brain Tumor Detection/requirement.txt
Labels: enhancement, level3, gssoc

#142 Pharmaceutical Drugs and Vitamins Images Detection
  Pharmaceutical Drugs and Vitamins Images Detection/Dataset/README.md
  Pharmaceutical Drugs and Vitamins Images Detection/Images/DenseNet121/87918c94-5dc8-410e-94f0-fd1f8d08ebff.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/DenseNet121/992a7274-9ea6-4757-ad0a-7c4e41805fae.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/DenseNet121/dfb74364-4379-4131-ae23-73e3c5e80d06.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/DenseNet121/f508171e-a64c-4b62-b1ed-9ce1fddb74c6.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/InceptionV3_predictions/02509165-66d3-4164-8f0d-1c6a8b57536a.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/InceptionV3_predictions/385088f1-0165-4ede-a392-c686b0904e29.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/InceptionV3_predictions/856f6215-1ccf-421a-be41-bdc7817b1590.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/InceptionV3_predictions/dd0bc14e-65d1-4726-979e-e89d2386a6eb.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/MobileNet_predictions/18b4bf42-2e21-4cd3-afc3-e7c672422e6e.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/MobileNet_predictions/20fd282c-2edc-48ce-8a52-c7d87a5089cb.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/MobileNet_predictions/982a84ee-788a-4bb2-89d5-4304a8a56eac.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/MobileNet_predictions/c35dcb78-6440-4864-98a6-3a2ea4cebb1b.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/Resnet50V2_predictions/13e67132-466a-472b-877e-0ed951a2809e.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/Resnet50V2_predictions/2d50be9e-1915-43a9-87ec-486c5d8c8ef5.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/Resnet50V2_predictions/3581db0f-bd7f-46d5-a93e-d47baced07bd.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/Resnet50V2_predictions/eb57435f-2201-4f0b-98da-b790e13750a6.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/Xception_predictions/1c85d549-30b2-4d7d-b720-85eb84ab1644.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/Xception_predictions/773ea5a9-7573-4057-968e-4fa8926af4cb.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/Xception_predictions/976ab080-7145-4f37-aa6a-73713f8a6a9e.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/Xception_predictions/ed06fe5c-e8a8-42d4-8d38-11da2ac72202.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/bar.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/image_path_distribution.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/pie_chart.png
  Pharmaceutical Drugs and Vitamins Images Detection/Models/README.md
  Pharmaceutical Drugs and Vitamins Images Detection/Models/models_Pharmaceutical_Drugs_and_Vitamins_Images_Detection_(1).ipynb
  Pharmaceutical Drugs and Vitamins Images Detection/requirement.txt
Labels: level3, gssoc

#116 Emotion-age-gender-confidence-detection-using-deepface-module
  Emotion-age-gender-race-detection-using-deepface-module/Emotion_recognition_with_Deepface_Module (1).ipynb
  Emotion-age-gender-race-detection-using-deepface-module/readme
Labels: level3, gssoc

#55 Added person detection for railway suicide prevention
  railway_person_detection/.gitignore
  railway_person_detection/README.md
  railway_person_detection/railway_person_detection.py
  railway_person_detection/requirements.txt
Labels: level3, gssoc

#106 added workflow as per issue #72
  .github/workflows/autocomment-pr-merge.yml
Labels: level1, gssoc

#92 here is my assigned PR please look into it issue no#73
  .DS_Store
  heart attack prediction/.DS_Store
  heart attack prediction/1.csv
  heart attack prediction/Readme.md
  heart attack prediction/heart_attack_model.pkl
  heart attack prediction/training by logistic regression.ipynb
  heart attack prediction/training_data.csv
Labels: good first issue, level1, gssoc

#157 Suicidal Post Detection Python App
  App.py
  SuicideDectection.ipynb
Labels: level3, gssoc

#152 Chest X-ray - Tuberculosis Disease Prediction
  Chest X-ray - Tuberculosis Disease Prediction/Dataset/README.md
  Chest X-ray - Tuberculosis Disease Prediction/Images/DenseNet121/07d23d26-602e-45b3-89a9-adc19a24a93b.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/DenseNet121/73a27086-f976-43d2-bbc3-34d1148e2cdd.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/DenseNet121/83be1e95-d591-41cb-b6a5-330af1de15c1.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/DenseNet121/941fe4f5-8176-4fc0-b2e5-1cc41e58138f.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/InceptionV3_predictions/01209f9f-e709-4a7a-a14b-97f98cdb16a6.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/InceptionV3_predictions/a970945f-aedf-4ac7-a4ee-e3f01fedcbb4.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/InceptionV3_predictions/b12522d2-e7f9-43bb-b9ec-0d862dfb3a2b.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/InceptionV3_predictions/b6627c83-2b71-411e-8a3b-ecb8a93b35f9.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/MobileNetV2_predictions/495e63b4-00da-42c1-9f88-21f74bcd083a.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/MobileNetV2_predictions/79b66dc3-b8f7-42fb-b782-4764d3bcbf54.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/MobileNetV2_predictions/cd214e19-6e33-4a6d-9d40-51a6fc182425.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/MobileNetV2_predictions/cef531b0-8c62-474d-8432-3b28d31586dd.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/Resnet50V2_predictions/09672514-0d74-4ba3-b83f-34b7dce90ce6.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/Resnet50V2_predictions/66b55d5b-c0dc-4c22-9c9d-574ad61aab1e.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/Resnet50V2_predictions/7df6144a-37f3-47d5-b42b-39a6d0e83ff4.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/Resnet50V2_predictions/c9365032-e058-4e78-93f9-e9654992bbf1.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/Xception_predictions/369f577f-fde9-48eb-a4ad-d9ee64a8f903.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/Xception_predictions/3c63b249-af3e-4732-8109-7595c30b09ec.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/Xception_predictions/bef2f489-15d6-4f72-a33e-5c306d33833f.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/Xception_predictions/cd93c4f3-2055-4daf-919a-9d88bf1d18ca.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/bar_chart.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/image_path_distribution.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/pie_chart.png
  Chest X-ray - Tuberculosis Disease Prediction/Models/README.md
  Chest X-ray - Tuberculosis Disease Prediction/Models/models_Chest_X_ray_Tuberculosis_Disease_Prediction(1).ipynb
  Chest X-ray - Tuberculosis Disease Prediction/requirement.txt
Labels: level3, gssoc

#153 Skin Lesion Images classification
  Skin Lesion Images classification/Dataset/README.md
  Skin Lesion Images classification/Images/DenseNet121/1d6bee1c-8aa1-4f63-9850-77629d02dc8d.png
  Skin Lesion Images classification/Images/DenseNet121/d0100609-bf58-45ef-a80f-227faf9c5781.png
  Skin Lesion Images classification/Images/DenseNet121/fa275f84-dbe2-45f2-b34a-ca0b0897443f.png
  Skin Lesion Images classification/Images/DenseNet121/fb7e6471-f268-4c15-be40-3f5ad694321e.png
  Skin Lesion Images classification/Images/InceptionV3_predictions/65d94200-3a53-4b44-8444-bd64f52630e3.png
  Skin Lesion Images classification/Images/InceptionV3_predictions/a5b82a5f-d123-4ced-b3e4-db220f42b7ff.png
  Skin Lesion Images classification/Images/InceptionV3_predictions/bd45fce8-a6ea-4b0c-979a-96c53f88be5a.png
  Skin Lesion Images classification/Images/InceptionV3_predictions/f761cd91-7790-43b7-96f3-7a9361e7f70a.png
  Skin Lesion Images classification/Images/MobileNetV2_predictions/94d85fd8-e41e-4b6e-bbea-8018e30dc41f.png
  Skin Lesion Images classification/Images/MobileNetV2_predictions/a2b36fa1-7611-4492-a89f-f229528a11e7.png
  Skin Lesion Images classification/Images/MobileNetV2_predictions/ad2cdd88-15cc-495e-bf9e-78cecb7b763a.png
  Skin Lesion Images classification/Images/MobileNetV2_predictions/c7940184-ec89-4478-991f-aaa8e7e8f69d.png
  Skin Lesion Images classification/Images/Resnet50V2_predictions/0c43d4e1-cd17-4cf2-842d-e4b0dc6a65d2.png
  Skin Lesion Images classification/Images/Resnet50V2_predictions/32f9234a-a912-4f29-9035-1d552b00e01f.png
  Skin Lesion Images classification/Images/Resnet50V2_predictions/a6d974c3-445f-4a6c-bb6c-bbdb21cea904.png
  Skin Lesion Images classification/Images/Resnet50V2_predictions/bb484090-43dd-47d7-9e99-a8a9d58672af.png
  Skin Lesion Images classification/Images/Xception_predictions/82a7a436-1879-44ca-8b62-3ca9ffc81fc1.png
  Skin Lesion Images classification/Images/Xception_predictions/8a31b924-8aae-4773-9b1f-e96e5eccf2d8.png
  Skin Lesion Images classification/Images/Xception_predictions/e228703d-a012-46bf-9176-8b95e206a7c9.png
  Skin Lesion Images classification/Images/Xception_predictions/e513cfae-9fb4-4089-b382-ec9f5dfeeca7.png
  Skin Lesion Images classification/Images/bar_chart.png
  Skin Lesion Images classification/Images/image_path_distribution.png
  Skin Lesion Images classification/Images/pie_chart.png
  Skin Lesion Images classification/Models/README.md
  Skin Lesion Images classification/Models/models_Skin_Lesion_Images_classification_final.ipynb
  Skin Lesion Images classification/requirement.txt
Labels: level3, gssoc

#63 Added UCB Content Recommendation System
  UCB Content Recommendation System/Code.py
  UCB Content Recommendation System/README.md
Labels: level1, gssoc

#170 Integration of Daily Mood Tracker Data into ThereForYou
  MoodSense/Dataset.csv
  MoodSense/MoodSense.ipynb
Labels: level2, gssoc

#169 Added Lung Cancer Detection Using Convolutional Neural Network: #164
  Lung Cancer Detection/Dataset/README.md
  Lung Cancer Detection/Models/Lung_Cancer_Detection.ipynb
  Lung Cancer Detection/Models/README.md
Labels: level3, gssoc

#168 [Feat]: Created Issue forms and made the issue options more visually appealing
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_update.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: good first issue, level1, gssoc

#178 Added Diabetes Prediction using machine learning: #175
  Diabetes Prediction/Dataset/dataset.csv
  Diabetes Prediction/Models/README.md
  Diabetes Prediction/Models/diabetes_prediction.ipynb
Labels: approved
