Repository TAHIR0110/ThereForYou, pull requests merged in 2024-08, with the labels that each got.

#340 Pneumonia Detection using X-Ray Images
  Pneumonia Detection using X-Ray Images/Dataset/Readme.md
  Pneumonia Detection using X-Ray Images/Images/Accuracy Graph CNN.png
  Pneumonia Detection using X-Ray Images/Images/Accuracy Graph Efficientnet50.png
  Pneumonia Detection using X-Ray Images/Images/CNN Result.png
  Pneumonia Detection using X-Ray Images/Images/Grayscale visuals.png
  Pneumonia Detection using X-Ray Images/Images/Loss Graph CNN.png
  Pneumonia Detection using X-Ray Images/Images/Loss Graph EfficientNet50.png
  Pneumonia Detection using X-Ray Images/Images/Matshow Image.png
  Pneumonia Detection using X-Ray Images/Models/Pneumonia Detection using X-Ray Images.ipynb
  Pneumonia Detection using X-Ray Images/Models/Pneumonia Detection via CNN.ipynb
  Pneumonia Detection using X-Ray Images/Readme.md
Labels: level2, gssoc

#326 Create code.py solved #304
  Students' stress and coping model/code.py
Labels: level1, gssoc

#334 Added HIV prediction using Machine Learning
  HIV Prediction using ML/HIV_Disease_Detection.ipynb
  HIV Prediction using ML/HIV_dataset.csv
  HIV Prediction using ML/app.py
  HIV Prediction using ML/readme.md
  HIV Prediction using ML/requirement.txt
  HIV Prediction using ML/xgboost_HIV_model.pkl
Labels: level2, gssoc

#328 added Food Nutrition Recommendation System
  Food Nutrition Recommendation System/Dataset/README.md
  Food Nutrition Recommendation System/Model/recommendation-system.ipynb
  Food Nutrition Recommendation System/README.md
Labels: level1, gssoc

#283 Sleep stagging classification
  Sleep Stagging Classification/Dataset/README.md
  Sleep Stagging Classification/Models/README.md
  Sleep Stagging Classification/Models/model.py
  Sleep Stagging Classification/requirements.txt
Labels: level3, gssoc

#335 Added Dementia Prediction using Machine learning
  Dementia Disease Detection using Machine learning/Dementia_Disease_detection_csv.ipynb
  Dementia Disease Detection using Machine learning/app.py
  Dementia Disease Detection using Machine learning/dementia_model.pkl
  Dementia Disease Detection using Machine learning/dementia_patients_health_data.csv
  Dementia Disease Detection using Machine learning/readme.md
  Dementia Disease Detection using Machine learning/requirement.txt
Labels: level2, gssoc

#338 Add Blood Cell Cancer Detection with CNN and EfficientNetB3
  Blood Cell Cancer Detection with CNN and EfficientNetB3/blood-cell-cancer-using-cnn-and-efficientnetb3.ipynb
Labels: level3, gssoc

#349 Added emotion detection feature based on text input
  Emotion Detection using Text/app.py
  Emotion Detection using Text/data/emotion_dataset_raw.csv
  Emotion Detection using Text/model/Text Emotion Detection.ipynb
  Emotion Detection using Text/model/text_emotion.pkl
Labels: level2, gssoc

#344 Added Epidemics Predictor
  Epidemics Predictor/IntelOptimisedDAAL_otherAlgorithms.ipynb
  Epidemics Predictor/Model_final.ipynb
  Epidemics Predictor/Readme.md
  Epidemics Predictor/other_models.ipynb
Labels: level2, gssoc

#342 Added DNA CLASSIFICATION
  DNA CLASSIFICATION/DNA_Classification_Code.ipynb
  DNA CLASSIFICATION/Readme.md
  DNA CLASSIFICATION/promoters.data
Labels: level2, gssoc

#309 Added Heart Disease Detection
  Heart Disease Detection/Dataset/heart_failure_clinical_records_dataset 2.csv
  Heart Disease Detection/Images/Result.png
  Heart Disease Detection/Images/metrics.png
  Heart Disease Detection/Images/model1_acc.png
  Heart Disease Detection/Images/model1_loss.png
  Heart Disease Detection/Images/model2_acc.png
  Heart Disease Detection/Images/model2_loss.png
  Heart Disease Detection/Images/model3_acc.png
  Heart Disease Detection/Images/model3_loss.png
  Heart Disease Detection/Images/summary_model.png
  Heart Disease Detection/Model/Heart_disease_prediction .ipynb
  Heart Disease Detection/README.md
  Heart Disease Detection/requirements.txt
Labels: level2, gssoc

#302 Body Fat Prediction
  Body Fat Prediction/BodyFatPrediction.ipynb
  Body Fat Prediction/Feature_Importance_score.ipynb
  Body Fat Prediction/Feature_importance.md
  Body Fat Prediction/Feature_importance_analysis.ipynb
  Body Fat Prediction/README.md
  Body Fat Prediction/bodyfat.csv
Labels: level2, gssoc

#297 Added Medical Charges for Smokers and Non-smoker
  Medical Charges for Smokers and Non-smoker/Medicine_Charges.ipynb
  Medical Charges for Smokers and Non-smoker/Readme.md
  Medical Charges for Smokers and Non-smoker/insurance.csv
Labels: level2, gssoc

#44 Heart_Disease_Prediction
  Heart_Disease_Prediction.ipynb
Labels: level2, gssoc

#108 Added instruction on how to use Github desktop
  CONTRIBUTING.md
Labels: level1, gssoc
