Repository TAHIR0110/ThereForYou, pull requests merged in 2024-07, with the labels that each got.

#239 Added Stroke Predication
  Stroke Prediction/Dataset/healthcare-dataset-stroke-data.csv
  Stroke Prediction/Model/README.md
  Stroke Prediction/Model/StrokePrediction-EDA.ipynb
Labels: level2, gssoc

#188 Added Fetal Health Detection
  Fetal Health Detection/Dataset/README.md
  Fetal Health Detection/Model/README.md
  Fetal Health Detection/Model/fetal-health-classification.ipynb
  Fetal Health Detection/requirements.txt
Labels: level2, gssoc

#245 Added Infant Health Prediction
  Infant Health Prediction/Dataset/Synthetic-Infant-Health-Data.csv
  Infant Health Prediction/Infant_health_predictions_EDA.ipynb
  Infant Health Prediction/README.md
Labels: level2, gssoc, approved

#165 Audio_Anamoly_detection
  Audio Anamoly detection/# Anomaly Detection with RNN Autoencoder.md
  Audio Anamoly detection/Audio_Anamoly_detection.ipynb
Labels: enhancement, level3, gssoc

#190 Solved Issue in autocommenting on merged pr #187
  .github/workflows/autocomment-pr-merge.yml
Labels: level1, gssoc

#186 Added Breast Cancer Detection: #176
  Breast Cancer Detection/Models/README.md
  Breast Cancer Detection/Models/breast_cancer_detection.ipynb
  Breast Cancer Detection/Models/dataset.csv
Labels: level2, gssoc

#227 Depression classification
  Depression Classification/Dataset/README.md
  Depression Classification/Models/README.md
  Depression Classification/Screenshot 2024-06-27 181113.png
  Depression Classification/Screenshot 2024-06-27 203925.png
  Depression Classification/Screenshot 2024-06-27 204232.png
  Depression Classification/Screenshot 2024-06-27 204248.png
  Depression Classification/Screenshot 2024-06-27 204305.png
  Depression Classification/Screenshot 2024-06-27 204320.png
  Depression Classification/Screenshot 2024-06-27 204728.png
  Depression Classification/Screenshot 2024-06-27 205000.png
  Depression Classification/Screenshot 2024-06-27 205133.png
  Depression Classification/Screenshot 2024-06-27 205346.png
  Depression Classification/Screenshot 2024-06-27 205408.png
  Depression Classification/Screenshot 2024-06-27 205427.png
  Depression Classification/Screenshot 2024-06-27 205501.png
  Depression Classification/requirements.txt
Labels: level3, gssoc

#145 [New Feature]: Automatic Number plate Recognition System for visually impaired
  Automatic Number Plate Recognition (ANPR) System/main.ipynb
  Automatic Number Plate Recognition (ANPR) System/sample images/Final.JPG
  Automatic Number Plate Recognition (ANPR) System/sample images/SS1.png
  Automatic Number Plate Recognition (ANPR) System/sample images/car.jpg
  Automatic Number Plate Recognition (ANPR) System/sample images/car2.jpg
  Automatic Number Plate Recognition (ANPR) System/sample images/logo.png
  Automatic Number Plate Recognition (ANPR) System/sample images/sample image.jpg
  Automatic Number Plate Recognition (ANPR) System/sample images/sample2.jpg
  Automatic Number Plate Recognition (ANPR) System/sample images/test.jpeg
  Automatic Number Plate Recognition (ANPR) System/sample images/test.jpg
  Automatic Number Plate Recognition (ANPR) System/sample images/test1.jpg
  Automatic Number Plate Recognition (ANPR) System/sample images/test2.jpg
  Automatic Number Plate Recognition (ANPR) System/sample images/test3.jpg
  Automatic Number Plate Recognition (ANPR) System/sample images/test4.jpg
Labels: level2, gssoc

#42 Update Blockchain-ML medical health .ipynb
  Blockchain-ML medical health .ipynb
Labels: level1, gssoc

#259 Added Metabolic Syndrome Prediction
  Metabolic Syndrome Prediction/Dataset/Metabolic Syndrome.csv
  Metabolic Syndrome Prediction/README.md
  Metabolic Syndrome Prediction/metabolic_syndrome_predict.ipynb
Labels: level2, gssoc, approved

#261 PTSD
  Post Traumatic Stress Detection/Dataset/README.md
  Post Traumatic Stress Detection/Model/main.py
  Post Traumatic Stress Detection/Model/train.py
  Post Traumatic Stress Detection/README.md
  Post Traumatic Stress Detection/requirements.txt
Labels: level2, gssoc

#258 Added Anemia Prediction
  Anemia Prediction/Dataset/Readme.md
  Anemia Prediction/Model/anemia_prediction.ipynb
  Anemia Prediction/Readme.md
Labels: level2, gssoc, approved

#263 Anxiety detection
  README.md
  ecg.py
  gsr_analysis.ipynb
  main.py
Labels: good first issue, level1, gssoc

#264 Endometrial Cancer Prediction
  Endometrial Cancer Prediction/Endometrial Cancer Prediction Dataset.ipynb
  Endometrial Cancer Prediction/README.md
  Endometrial Cancer Prediction/Uterine Corpus Endometrial Carcinoma dataset.csv
Labels: level2, gssoc

#282 Added Chronic-Kidney-Disease-Prediction-using-ANN-with-Normalization
  Chronic-Kidney-Disease-Prediction/Chronic_kidney_disease_prediction.ipynb
  Chronic-Kidney-Disease-Prediction/Readme.md
  Chronic-Kidney-Disease-Prediction/kidney_disease_dataset.csv
Labels: level3, gssoc

#289 added Suicide & Depression Detection
  Suicide & Depression Detection/Dataset/README.md
  Suicide & Depression Detection/Images/GRU_Accuracy_Plot.png
  Suicide & Depression Detection/Images/Model_LSTMs_Accuracy.png
  Suicide & Depression Detection/Images/Top 50 words.png
  Suicide & Depression Detection/Images/WordCloud.png
  Suicide & Depression Detection/Models/suicidal-content-detection-using-gru.ipynb
  Suicide & Depression Detection/Models/suicidal-ideation-detection-bilstm-rnn.ipynb
  Suicide & Depression Detection/README.md
Labels: level2, gssoc

#279 Added Cervical Cancer Classification
  Cervical Cancer Classification/cervical-cancer-classification.ipynb
  Cervical Cancer Classification/readME.md
Labels: level2, gssoc, approved

#290 Student Anxiety and Depression Model
  Student Anxiety and Depression Model/read.md
  Student Anxiety and Depression Model/students-anxiety-and-depression-classify-model.ipynb
Labels: level2, gssoc

#300 Hindi letter classification Project
  Hindi_Letter_Classification/Dataset/README.md
  Hindi_Letter_Classification/Dataset/Test/character_10_jha.png
  Hindi_Letter_Classification/Dataset/Test/character_1_ka.png
  Hindi_Letter_Classification/Dataset/Test/character_2_kha.png
  Hindi_Letter_Classification/Dataset/Test/character_3_ga.png
  Hindi_Letter_Classification/Dataset/Test/character_4_gha.png
  Hindi_Letter_Classification/Dataset/Test/character_5_da.png
  Hindi_Letter_Classification/Dataset/Test/character_6_dha.png
  Hindi_Letter_Classification/Dataset/Test/character_7_chha.png
  Hindi_Letter_Classification/Dataset/Test/character_8_cha.png
  Hindi_Letter_Classification/Dataset/Test/character_9_ja.png
  Hindi_Letter_Classification/Dataset/Test/digit_0.png
  Hindi_Letter_Classification/Dataset/Test/digit_1.png
  Hindi_Letter_Classification/Dataset/Test/digit_3.png
  Hindi_Letter_Classification/Dataset/Test/digit_4.png
  Hindi_Letter_Classification/Dataset/Test/digit_5.png
  Hindi_Letter_Classification/Dataset/Test/digit_6.png
  Hindi_Letter_Classification/Dataset/Test/digit_7.png
  Hindi_Letter_Classification/Dataset/Test/digit_9.png
  Hindi_Letter_Classification/Dataset/Train/character_10_jha.png
  Hindi_Letter_Classification/Dataset/Train/character_1_ka.png
  Hindi_Letter_Classification/Dataset/Train/character_2_kha.png
  Hindi_Letter_Classification/Dataset/Train/character_3_ga.png
  Hindi_Letter_Classification/Dataset/Train/character_4_gha.png
  Hindi_Letter_Classification/Dataset/Train/character_5_da.png
  Hindi_Letter_Classification/Dataset/Train/character_6_dha.png
  Hindi_Letter_Classification/Dataset/Train/character_7_chha.png
  Hindi_Letter_Classification/Dataset/Train/character_8_cha.png
  Hindi_Letter_Classification/Dataset/Train/character_9_ja.png
  Hindi_Letter_Classification/Dataset/Train/digit_0.png
  Hindi_Letter_Classification/Dataset/Train/digit_1.png
  Hindi_Letter_Classification/Dataset/Train/digit_3.png
  Hindi_Letter_Classification/Dataset/Train/digit_4.png
  Hindi_Letter_Classification/Dataset/Train/digit_5.png
  Hindi_Letter_Classification/Dataset/Train/digit_6.png
  Hindi_Letter_Classification/Dataset/Train/digit_7.png
  Hindi_Letter_Classification/Dataset/Train/digit_9.png
  Hindi_Letter_Classification/Dataset/Web_app.ipynb
  Hindi_Letter_Classification/Dataset/class_indexes.txt
  Hindi_Letter_Classification/Dataset/single_prediction/test10.jpg
  Hindi_Letter_Classification/Dataset/single_prediction/test11.png
  Hindi_Letter_Classification/Dataset/single_prediction/test4.png
  Hindi_Letter_Classification/Dataset/single_prediction/test5.png
  Hindi_Letter_Classification/Dataset/single_prediction/test6.png
  Hindi_Letter_Classification/Dataset/single_prediction/test7.png
  Hindi_Letter_Classification/Dataset/single_prediction/test8.png
  Hindi_Letter_Classification/Dataset/single_prediction/test9.png
  Hindi_Letter_Classification/Dataset/single_prediction/tset12.png
Labels: level2, gssoc

#321 SuicidalDetection.py enhancement #issue 274
  Suicide & Depression Detection/Models/SuicidalDetection.py
Labels: level2, gssoc

#333 Added Food Allergy Prediction
  Food Allergy Prediction/Food_Allergy_Prediction.ipynb
  Food Allergy Prediction/Readme.md
  Food Allergy Prediction/food allergy data.csv
Labels: level2, gssoc

#306 Integration of ML/DL into android.
  Flower_Classification_Android_App/.idea/.gitignore
  Flower_Classification_Android_App/.idea/codeStyles/Project.xml
  Flower_Classification_Android_App/.idea/codeStyles/codeStyleConfig.xml
  Flower_Classification_Android_App/.idea/compiler.xml
  Flower_Classification_Android_App/.idea/deploymentTargetDropDown.xml
  Flower_Classification_Android_App/.idea/gradle.xml
  Flower_Classification_Android_App/.idea/misc.xml
  Flower_Classification_Android_App/.idea/vcs.xml
  Flower_Classification_Android_App/app/.gitignore
  Flower_Classification_Android_App/app/build.gradle
  Flower_Classification_Android_App/app/gradle/.gitignore
  Flower_Classification_Android_App/app/gradle/README.md
  Flower_Classification_Android_App/app/gradle/build.gradle
  Flower_Classification_Android_App/app/gradle/gradle.properties
  Flower_Classification_Android_App/app/gradle/gradlew
  Flower_Classification_Android_App/app/gradle/gradlew.bat
  Flower_Classification_Android_App/app/gradle/iris.data
  Flower_Classification_Android_App/app/gradle/model.py
  Flower_Classification_Android_App/app/gradle/settings.gradle
  Flower_Classification_Android_App/app/gradle/wrapper/gradle_wrapper.properties
  Flower_Classification_Android_App/app/progaurd-rules.pro
  Flower_Classification_Android_App/app/src/androidTest/ExampleInstrumentedTest.kt
  Flower_Classification_Android_App/app/src/main/AndroidManifest.xml
  Flower_Classification_Android_App/app/src/main/java/com/example/MainActivity.kt
  Flower_Classification_Android_App/app/src/main/java/com/example/flower/ExampleUnitTest.kt
  Flower_Classification_Android_App/app/src/res/drawable-v24/ic_launcher_foreground.xml
  Flower_Classification_Android_App/app/src/res/drawable/ic_launcher_background.xml
  Flower_Classification_Android_App/app/src/res/layout/activity_main.xml
  Flower_Classification_Android_App/app/src/res/mipmap-anydpi-v26/ic_launcher.xml
  Flower_Classification_Android_App/app/src/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Flower_Classification_Android_App/app/src/res/values-night/themes.xml
  Flower_Classification_Android_App/app/src/res/values/colors.xml
  Flower_Classification_Android_App/app/src/res/values/strings.xml
  Flower_Classification_Android_App/app/src/res/values/themes.xml
  Flower_Classification_Android_App/app/src/res/xml/backup_rules.xml
  Flower_Classification_Android_App/app/src/res/xml/data_extraction_rules.xml
Labels: level2, gssoc
